### ISSUE TITLE
[BUG] Result title with forbidden chars error

### ISSUE THREAD

**Issue by matthieu42morin** [StrangeGirlMurph/obsidian-wikipedia-search#30]
When searching for something that outputs a result title with "" from wikipedia, this is the error upon trying to create the note:

Uncaught (in promise) Error: File name cannot contain any of the following characters: * " \ / < > : | ?
    at mb (app.js:1:718134)
    at t.checkPath (app.js:1:725357)
    at t.<anonymous> (app.js:1:727242)
    at app.js:1:237544
    at Object.next (app.js:1:237649)
    at app.js:1:236565
    at new Promise (<anonymous>)
    at v (app.js:1:236310)
    at t.create (app.js:1:727130)
    at createNoteInFolder (plugin:wikipedia-search:603:22)"
    at async createArticleNote (plugin:wikipedia-search:2659:20)

# To Reproduce

Just do above

# Expected Behavior

Should delete quotes or change them to -

# Additional Info

I am making a pull request

**Comment by matthieu42morin** [comment]
oh an example would be ["Hello, World!" program](https://en.wikipedia.org/wiki/%22Hello,_World!%22_program)
